/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package binarytreeproject_spagnola;
import org.jsoup.Jsoup;
import java.awt.Component;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Jim
 */
public class ProjectWindow extends javax.swing.JFrame {
    URLHasher hasher;
    /**
     * Creates new form ProjectWindow
     */
    public ProjectWindow(URLHasher inHasher) {
        hasher = inHasher;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        classPanel = new javax.swing.JPanel();
        barbarianLabel = new javax.swing.JLabel();
        bardLabel = new javax.swing.JLabel();
        clericLabel = new javax.swing.JLabel();
        druidLabel = new javax.swing.JLabel();
        monkLabel = new javax.swing.JLabel();
        fighterLabel = new javax.swing.JLabel();
        sorcererLabel = new javax.swing.JLabel();
        rogueLabel = new javax.swing.JLabel();
        wizardLabel = new javax.swing.JLabel();
        warlockLabel = new javax.swing.JLabel();
        paladinLabel = new javax.swing.JLabel();
        rangerLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        websiteField = new javax.swing.JTextField();
        goButton = new javax.swing.JButton();
        testButton = new javax.swing.JButton();
        resultsPanel = new javax.swing.JPanel();
        similarClassLabel = new javax.swing.JLabel();
        similarityLabel = new javax.swing.JLabel();
        classLabel = new javax.swing.JLabel();
        frequencyLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HashTable Project");

        classPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        barbarianLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barbarianLabel.setText("Barbarian");
        barbarianLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bardLabel.setText("Bard");
        bardLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        clericLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clericLabel.setText("Cleric");
        clericLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        druidLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        druidLabel.setText("Druid");
        druidLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        monkLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monkLabel.setText("Monk");
        monkLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        fighterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fighterLabel.setText("Fighter");
        fighterLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sorcererLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sorcererLabel.setText("Sorcerer");
        sorcererLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rogueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rogueLabel.setText("Rogue");
        rogueLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        wizardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wizardLabel.setText("Wizard");
        wizardLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        warlockLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warlockLabel.setText("Warlock");
        warlockLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        paladinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paladinLabel.setText("Paladin");
        paladinLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rangerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rangerLabel.setText("Ranger");
        rangerLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout classPanelLayout = new javax.swing.GroupLayout(classPanel);
        classPanel.setLayout(classPanelLayout);
        classPanelLayout.setHorizontalGroup(
            classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barbarianLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(druidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clericLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fighterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paladinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sorcererLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rogueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rangerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wizardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warlockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        classPanelLayout.setVerticalGroup(
            classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barbarianLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clericLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(druidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(fighterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paladinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rangerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rogueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sorcererLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(warlockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wizardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        titleLabel.setText("DND Class Frequency Table");

        goButton.setText("GO!");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        testButton.setText("Test");
        testButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testButtonActionPerformed(evt);
            }
        });

        resultsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        similarClassLabel.setText("Most Similar Class:");

        similarityLabel.setText("Similarity:");

        classLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        frequencyLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout resultsPanelLayout = new javax.swing.GroupLayout(resultsPanel);
        resultsPanel.setLayout(resultsPanelLayout);
        resultsPanelLayout.setHorizontalGroup(
            resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(similarClassLabel)
                    .addComponent(similarityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(frequencyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(classLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        resultsPanelLayout.setVerticalGroup(
            resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(similarClassLabel)
                    .addComponent(classLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frequencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(similarityLabel))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(classPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(testButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(websiteField)
                            .addComponent(resultsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(websiteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(goButton)
                            .addComponent(testButton))
                        .addGap(28, 28, 28)
                        .addComponent(resultsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(classPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed
        // TODO add your handling code here:
        String testURL = "https://roll20.net/compendium/dnd5e/Elf#content";
        try{
        hasher.hashURL(testURL);
        }
        catch(IOException e){
            Component frame;
            JOptionPane.showMessageDialog( null, "You have entered an Invalid URL");
        }
        presentData();
    }//GEN-LAST:event_testButtonActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        // TODO add your handling code here:
        
        try{ 
            hasher.hashURL(websiteField.getText());       
            presentData();  
        }
        catch(Exception e){
            JOptionPane.showMessageDialog( null, "You have entered an Invalid URL");
        }

    }//GEN-LAST:event_goButtonActionPerformed
    
    private void presentData(){
        URLTable table = hasher.getMostSimilarURL();
        String name = getClassName(table.url);
        classLabel.setText(name);
        frequencyLabel.setText(""+ table.comparability);
        
    }
    
    private String getClassName(String url){
        String name;
        if(url.contains("Barbarian"))
            name = "Barbarian";
        else if(url.contains("Bard"))
            name = "Bard";
        else if(url.contains("Cleric"))
            name = "Cleric";
        else if(url.contains("Druid"))
            name = "Druid";
        else if(url.contains("Fighter"))
            name = "Fighter";
        else if(url.contains("Monk"))
            name = "Monk";
        else if(url.contains("Paladin"))
            name = "Paladin";
        else if(url.contains("Ranger"))
            name = "Ranger";
        else if(url.contains("Rogue"))
            name = "Rogue";
        else if(url.contains("Sorcerer"))
            name = "Sorcerer";
        else if(url.contains("Warlock"))
            name = "Warlock";
        else if(url.contains("Wizard"))
            name = "Wizard";
        else
            name = "Error";
        return name;
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barbarianLabel;
    private javax.swing.JLabel bardLabel;
    private javax.swing.JLabel classLabel;
    private javax.swing.JPanel classPanel;
    private javax.swing.JLabel clericLabel;
    private javax.swing.JLabel druidLabel;
    private javax.swing.JLabel fighterLabel;
    private javax.swing.JLabel frequencyLabel;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel monkLabel;
    private javax.swing.JLabel paladinLabel;
    private javax.swing.JLabel rangerLabel;
    private javax.swing.JPanel resultsPanel;
    private javax.swing.JLabel rogueLabel;
    private javax.swing.JLabel similarClassLabel;
    private javax.swing.JLabel similarityLabel;
    private javax.swing.JLabel sorcererLabel;
    private javax.swing.JButton testButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel warlockLabel;
    private javax.swing.JTextField websiteField;
    private javax.swing.JLabel wizardLabel;
    // End of variables declaration//GEN-END:variables
}
